# ruff.toml

line-length = 88
target-version = "py311"

[lint]
select = [
    "E",
    "F",
    "W",
    "I",
    "N",
    "UP",
    "B",
    "A",
    "C4",
    "DJ",
    "T",
    "PERF",
    "D101",
]
ignore = ["D100", "D102", "D103"]

[lint.per-file-ignores]
"*/tests/*.py" = ["S101"]
"*/migrations/*.py" = ["ALL"]

[lint.isort]
known-first-party = ["your_project"]
combine-as-imports = true

[lint.isort.sections]
future = ["__future__"]
stdlib = ["os", "sys"]
thirdparty = ["django", "rest_framework"]
firstparty = ["your_project"]
localfolder = ["."]
